config/routes.rb
Rails.application.routes.draw do
  resources :hospitals do
    resources :patients do
      resources :meds 
    end
  end

  root 'home#index'

  

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
  validates :name,     presence: true
  validates :address1, presence: true
  validates :address2, presence: true
  validates :city,     presence: true
  validates :state,    presence: true
  validates :zip,      presence: true
  validates :phone,    presence: true


  has_many  :patients, dependent:  :destroy

end

app/models/med.rb
class Med < ActiveRecord::Base
belongs_to :patient

  validates :med_name, presence: true
  validates :med_class, presence: true
  validates :med_dosage, presence: true
  validates :med_use, presence: true

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :hospital

    validates :first_name,  presence:   true
    validates :last_name,  presence:   true
    validates :description,  presence:   true
    validates :blood_type,  presence:   true
    validate :at_least_10

  has_many  :meds, dependent:  :destroy

      def at_least_10
        if self.date_of_birth
          errors.add(:date_of_birth, ' , Must be at least 10 years old!') if self.date_of_birth > 10.years.ago.to_date
        end
      end

  BLOOD_TYPE = [
    "O",
    "O+",
    "A",
    "A-",
    "B",
    "B-",
    "AB"
  ]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
before_action :set_hospital, only:[:show, :edit, :update, :destroy]

  def index
    @hospitals = Hospital.all 
  end

  def new
    @hospital = Hospital.new
  end

  def edit
  end

  def create
    @hospital = Hospital.new(hospital_params)
    if @hospital.save
    flash[:notice] = "Hospital was successfully added"
    redirect_to hospitals_path
    else
      flash[:error] = "Hospital was not added!"
      render :new
    end
  end

   def show
      @patients = @hospital.patients
    end

  def update
    respond_to do |format|
      if @hospital.update(hospital_params)
        format.html {redirect_to @hospital, notice: "Hospital Information Was Updated!"}
        format.json {render :show, status: :ok, location: @hospital }
      else
        format.html {render :edit}
        format.json {render json: @hospital.errors, status: :unprocessable_entity }
      end
  end
end

  def destroy
    @hospital.destroy
      respond_to do |format|
      format.html {redirect_to hospitals_url, notice: "Hospital was Removed!!"}
      format.json {head :no_content }
      end      
  end

  private
  def set_hospital
    @hospital = Hospital.find(params[:id])
  end

  def hospital_params
    params.require(:hospital).permit(
      :name,
      :address1,
      :address2,
      :city,    
      :state,   
      :zip,     
      :phone
    )
  end

end

app/controllers/meds_controller.rb
class MedsController < ApplicationController
 before_action :set_med                                     

  def index
    # @patient = Patient.find params[:patient_id]
    @meds = @patient.meds
  end

  def show
    # @hospital = Hospital.find params[:hospital_id]
    @med = Med.find params[:id]
  end

  def new
    # @hospital = Hospital.find params[:hospital_id]
    # @patient = Patient.find params[:patient_id]
    @med = @patient.meds.new 
  end

  def create
    # @hospital = Hospital.find params[:hospital_id]
    # @patient = Patient.find params[:patient_id]
    @patient.meds.create med_params
    redirect_to hospital_patient_path(@hospital, @patient)
  end

  def edit
    @med = Med.find params[:id]
  end

  def update
    @med = Med.find params[:id]
    # @hospital = Hospital.find params[:hospital_id]
    # @patient = Patient.find params[:patient_id]
    @med.update_attributes med_params
    redirect_to hospital_patient_path(@hospital, @patient)
  end

  def destroy
    @med = Med.find params[:id]
    @med.delete
    # @hospital = Hospital.find params[:hospital_id]
    # @patient = Patient.find params[:patient_id]
    redirect_to hospital_patient_path(@hospital, @patient)
  end

private
  def med_params
    params.require(:med).permit(
        :med_name,
        :med_class,
        :med_dosage,
        :med_use,
        )
    end

  def set_med
    @hospital = Hospital.find params[:hospital_id]
    @patient = Patient.find params[:patient_id]
    
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
before_action :set_hospital
before_action :set_patient, only:[:show, :edit, :update, :destroy]

  def index
    @patients = Patient.all
  end

  def show
    @meds = @patient.meds
  end

  def new
    @patient = @hospital.patients.new
  end

  def create
    @patient = @hospital.patients.create patient_params
    redirect_to hospital_path(@hospital)
  end

  def edit
  end

  def update
    @patient.update_attributes (patient_params)
      redirect_to hospital_patients_path
  end

  def destroy
    @patient.delete
    redirect_to hospital_patients_path
  end

private
    def patient_params
      params.require(:patient).permit(
        :first_name,
        :last_name,
        :date_of_birth,
        :description,
        :gender,
        :blood_type
        )
    end

    def set_hospital
      @hospital = Hospital.find params[:hospital_id]
    end

    def set_patient
      @patient = Patient.find params[:id]
    end
      
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/meds_helper.rb
module MedsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/index.html.erb
<h1>Welcome to The Greenville Health system</h1>

app/views/hospitals/_form.html.erb
<%= form_for(@hospital) do |f| %>

  <% if @hospital.errors.any? %>
  <% @hospital.errors.full_messages.each do |message| %>
  <%= message %><br>
  <% end %>
  <% end %>

  <div class = "field">
    <%=f.label :name %>
    <%=f.text_field :name %><br>
  </div>

  <div class = "field">
    <%=f.label :address1 %>
    <%=f.text_field :address1 %><br>
  </div>

  <div class = "field">
    <%=f.label :address2 %>
    <%=f.text_field :address2 %><br>
  </div>

  <div class = "field">
    <%=f.label :city %>
    <%=f.text_field :city %>
  </div>

  <div class = "field">
    <%=f.label :state %>
    <%=f.text_field :state %><br>
  </div>

  <div class = "field">
    <%=f.label :zip %>
    <%=f.text_field :zip %><br>
  </div>

  <div class = "phone">
    <%=f.label :phone %>
    <%=f.text_field :phone %><br>
  </div>

  <div class= "actions">
    <%= f.submit %>
  </div>
  <% end %>

app/views/hospitals/edit.html.erb
<h1>Hospital Edit Page</h1>

<%= render "form" %>

<%= link_to "Show", @hospital %>
<%= link_to "Hospital Home", hospitals_path %>

app/views/hospitals/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Hospital Listing</h1>
<br>
<br>
<% @hospitals.each do |hospital| %>
   <li>
<%= hospital.name %><br>
<%= hospital.address1 %><br>
<%= hospital.address2 %><br>
<%= hospital.city %>,
<%= hospital.state %>
<%= hospital.zip %><br>
<%= number_to_phone(hospital.phone, area_code: true)%>
 </li>
<%= link_to "Show Details", hospital_path(hospital) %>
<%= link_to "Edit", edit_hospital_path(hospital) %>
<%= link_to "Delete", hospital, method: :delete, data: {confirm: "Are you certain you want to delete this location and all of its data?"} %><br><br>
<% end %><br>

<%= link_to "New Hospital", new_hospital_path %>

app/views/hospitals/new.html.erb
<h1>New Hospital</h1>

<%= render "form" %>

<%= link_to "Cancel", hospitals_path %>

app/views/hospitals/show.html.erb
<p>
<strong>Hospital Name: </strong>
<%= @hospital.name %><br>
<strong>Address 1: </strong>
<%= @hospital.address1 %><br>
<strong>Address 2: </strong>
<%= @hospital.address2 %><br>
<strong>City: </strong>
<%= @hospital.city %>
<strong>   State:  </strong>
<%= @hospital.state %><br>
<strong>Zip: </strong>
<%= @hospital.zip %><br>
<strong>Phone: </strong>
<%= number_to_phone(@hospital.phone, area_code: true) %>
</p>

<p>
  <strong>Patient Listing</strong><br>
<ul>
  <% @patients.each do |patient| %>
  <li><%= patient.first_name %>
    <%= patient.last_name %><br>
    <%= patient.gender %><br>
    DOB:  <%= patient.date_of_birth %><br>
    Symptoms: <%= patient.description %><br>
    Blood Type: <%= patient.blood_type %> <br>
    <%= link_to "Patient Details", hospital_patient_path(@hospital, patient) %>
  </li>
  <br>
  <br>
  <% end%>
</ul>
<%= link_to "Add Patient", new_hospital_patient_path(@hospital) %>

</p>

<%= link_to "Edit Hospital", edit_hospital_path(@hospital) %><br>
<%= link_to "Hospital Listing", hospitals_path %><br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hospitalv1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home", root_path %>
<%= link_to "Hospital List", hospitals_path %>

 <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>

  <% if flash[:error] %>
    <p id="error"><%= flash[:error] %></p>
  <% end %>
<%= yield %>

</body>
</html>

app/views/meds/_form.html.erb
<br>
<%= form_for [@hospital, @patient, @med] do |f| %>

  <%= f.label :med_name %>
  <%= f.text_field :med_name %>
  <br>
  <%= f.label :med_class %>
  <%= f.text_field :med_class %>
  <br>
  <%= f.label :med_dosage %>
  <%= f.text_field :med_dosage %>
  <br>
  <%= f.label :med_use %>
  <%= f.text_field :med_use %>
  <br>

  <br>
<%= f.submit %>
<% end %>

app/views/meds/edit.html.erb
<h1>Edit Medicine</h1>

<%= render "form" %>

app/views/meds/new.html.erb
<h1>Pharmaceuticals</h1>

<%= render "form" %>
<%= link_to "Cancel", hospital_patients_path(@hospital, @patient) %>
  <br>
 

app/views/patients/_form.html.erb
<br>

  <%= form_for [@hospital, @patient] do |f| %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>
  <%= f.label :date_of_birth %>
  <%= f.date_field :date_of_birth %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.label :gender %>
  <%= f.radio_button :gender, "Male" %>
  <%= label :gender_male, 'Male' %>
  <%= f.radio_button :gender, "Female" %>
  <%= label :gender_female, 'Female' %>
  <br>
  <%= f.label :blood_type %>
  <%= f.select :blood_type, options_for_select(Patient::BLOOD_TYPE, @patient.blood_type), include_blank: "--- Select ---" %>
  <br>
<%= f.submit %>

<%= link_to "Cancel", hospital_path(@hospital) %>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient</h1>

<%= render 'form' %>

app/views/patients/index.html.erb
<h1>Patient List</h1>

<%= link_to "Home", root_path %>
<%= link_to "New Patient", new_hospital_patient_path %>

  <ul>
    <% @patients.each do |patient| %>
    <li>
      First Name: <%= patient.first_name %><br>
      Last Name: <%= patient.last_name %><br>
      Birth Date: <%= patient.date_of_birth %><br>
      Symptom: <%= patient.description %><br>
      Gender: <%= patient.gender %><br>
      Blood Type: <%= patient.blood_type %>
    
    <%= link_to "Edit", edit_hospital_patient_path(@hospital, patient) %>
    <%= link_to "Delete", hospital_patient_path(@hospital, patient), method: :delete %><br>
    </li>
    <% end %>
  </ul>
   <br>
   

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form' %>

app/views/patients/show.html.erb
<p>
<strong>Name: </strong>
<%= @patient.first_name %>
<%= @patient.last_name %><br>
<strong>Date of Birth: </strong>
<%= @patient.date_of_birth %><br>
<strong>Problem Description: </strong>
<%= @patient.description %><br>
<strong>Gender:  </strong>
<%= @patient.gender %><br>
<strong>Blood Type: </strong>
<%= @patient.blood_type %>
</p>

<p>
  <strong>Medicine Listing</strong><br>
  <ul>
    <% @meds.each do |med| %>
    <li><%= med.med_name %> <br> Classification:  <%= med.med_class %> <br> Dosage: <%= med.med_dosage %> <br> Medical Use: <%= med.med_use %> </li>
    <%= link_to "Edit Med", edit_hospital_patient_med_path(@hospital, @patient, med)%>
    <%= link_to "Delete", hospital_patient_med_path(@hospital, @patient, med), method: :delete %><br>
    <% end%>
  </ul>
</p>
<%= link_to "Add Medicine", new_hospital_patient_med_path(@hospital, @patient) %><br>
<%= link_to "Edit Patient", edit_hospital_patient_path(@hospital, @patient) %><br>
<%= link_to "Patient Listing", hospital_path(@hospital) %><br>
<br>